import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { startAuthentication, startRegistration } from '@simplewebauthn/browser';
import { AreaChart, Area, BarChart, Bar, Cell, CartesianGrid, Tooltip, XAxis, YAxis, ResponsiveContainer, PieChart, Pie, Legend, ReferenceDot } from 'recharts';
import './styles.css';

const AUD = new Intl.NumberFormat('en-AU', { style: 'currency', currency: 'AUD' });
const money = (v, currency='AUD') => v == null ? '—' : new Intl.NumberFormat('en-AU', { style:'currency', currency }).format(v);
const pct = v => v == null ? '—' : `${v.toFixed(1)}%`;
const today = () => new Date().toISOString().slice(0,10);
async function api(path, options={}) {
  const res = await fetch(path, { credentials:'include', headers:{'Content-Type':'application/json', ...(options.headers||{})}, ...options });
  if (!res.ok) throw new Error(await res.text());
  return res.json();
}
function App(){
 const [auth,setAuth]=useState(null); const [error,setError]=useState('');
 const refreshAuth=()=>api('/api/auth/status').then(setAuth).catch(e=>setError(e.message));
 useEffect(()=>{refreshAuth(); if('serviceWorker' in navigator) navigator.serviceWorker.register('/sw.js');},[]);
 if(!auth) return <Shell><p>Loading…</p></Shell>;
 if(!auth.authenticated) return <Shell><AuthPanel auth={auth} onDone={refreshAuth} setError={setError}/>{error&&<p className="error">{error}</p>}</Shell>;
 return <Dashboard onLogout={async()=>{await api('/api/auth/logout',{method:'POST'});refreshAuth();}} />
}
function Shell({children}){return <main className="app"><header><div><p className="eyebrow">Private dashboard</p><h1>Cashflow</h1></div></header>{children}</main>}
function AuthPanel({auth,onDone,setError}){
 const [device,setDevice]=useState('iPhone / device');
 async function register(){try{const opts=await api('/api/auth/register/first/options',{method:'POST',body:JSON.stringify({name:device})}); const credential=await startRegistration({ optionsJSON: opts }); await api('/api/auth/register/verify',{method:'POST',body:JSON.stringify({credential,deviceName:device})}); onDone();}catch(e){setError(e.message)}}
 async function login(){try{const opts=await api('/api/auth/login/options',{method:'POST'}); const credential=await startAuthentication({ optionsJSON: opts }); await api('/api/auth/login/verify',{method:'POST',body:JSON.stringify({credential})}); onDone();}catch(e){setError(e.message)}}
 return <section className="card auth"><h2>{auth.has_passkey?'Unlock with passkey':'First run: register your passkey'}</h2><p>Passkeys only work at <strong>https://{auth.rp_id}</strong> with the original Host header forwarded.</p>{!auth.has_passkey&&<input value={device} onChange={e=>setDevice(e.target.value)} placeholder="Device name"/>}<button onClick={auth.has_passkey?login:register}>{auth.has_passkey?'Sign in with passkey':'Create owner passkey'}</button></section>
}
function Dashboard({onLogout}){const [data,setData]=useState(null); const [anchors,setAnchors]=useState([]); const [cashflows,setCashflows]=useState([]); const [holdings,setHoldings]=useState([]); const [portfolio,setPortfolio]=useState(null); const load=async()=>{setData(await api('/api/cash/summary'));setAnchors(await api('/api/anchors'));setCashflows(await api('/api/cashflows'));setHoldings(await api('/api/holdings'));setPortfolio(await api('/api/portfolio'));}; useEffect(()=>{load()},[]); if(!data) return <Shell><p>Loading dashboard…</p></Shell>; return <Shell><div className="actions"><button className="ghost" onClick={async()=>{const name=prompt('Passkey device name','Additional device'); if(!name)return; const opts=await api('/api/auth/register/options',{method:'POST',body:JSON.stringify({name})}); const credential=await startRegistration({ optionsJSON: opts }); await api('/api/auth/register/verify',{method:'POST',body:JSON.stringify({credential,deviceName:name})}); alert('Passkey registered');}}>Add passkey</button><button className="ghost" onClick={onLogout}>Logout</button></div><CashSection data={data} reload={load}/><ManageCash anchors={anchors} cashflows={cashflows} reload={load}/><PortfolioSection holdings={holdings} portfolio={portfolio} reload={load}/></Shell>}
function CashSection({data,reload}){const [amount,setAmount]=useState(''); const trough=data.forecast.trough; const peak=data.forecast.peak; async function overwrite(){if(amount==='')return; await api('/api/cash/overwrite',{method:'POST',body:JSON.stringify({amount:Number(amount),note:'Overwrite balance as of today'})}); setAmount(''); reload();}
 return <section className="grid"><div className="card hero"><p className="eyebrow">Calculated cash balance today</p><h2>{AUD.format(data.balance??0)}</h2><p>Based on anchor {data.anchor?`${data.anchor.date} (${AUD.format(data.anchor.amount)})`:'—'}</p><div className="inline"><input type="number" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Overwrite today"/><button onClick={overwrite}>Overwrite balance as of today</button></div></div><div className={`card metric ${trough?.balance<=0?'danger':''}`}><p className="eyebrow">Forecast trough</p><h3>{money(trough?.balance)}</h3><p>{trough?.date}</p></div><div className="card metric"><p className="eyebrow">Forecast peak</p><h3>{money(peak?.balance)}</h3><p>{peak?.date}</p></div><div className="card wide"><h2>60-day forecast</h2><ResponsiveContainer width="100%" height={320}><AreaChart data={data.forecast.points}><defs><linearGradient id="cash" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#38bdf8" stopOpacity={0.55}/><stop offset="95%" stopColor="#38bdf8" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke="#233047"/><XAxis dataKey="date" tick={{fill:'#9fb1c8',fontSize:11}}/><YAxis tickFormatter={v=>`$${Math.round(v/1000)}k`} tick={{fill:'#9fb1c8'}}/><Tooltip content={({active,payload,label})=>active&&payload?.length?<div className="tip"><b>{label}</b><p>{money(payload[0].value)}</p>{payload[0].payload.transactions.map((t,i)=><p key={i}>{t.label}: {money(t.amount)}</p>)}</div>:null}/><Area type="monotone" dataKey="balance" stroke="#38bdf8" fill="url(#cash)" strokeWidth={3}/>{trough&&<ReferenceDot x={trough.date} y={trough.balance} r={6} fill="#fb7185" stroke="white"/>}{peak&&<ReferenceDot x={peak.date} y={peak.balance} r={6} fill="#22c55e" stroke="white"/>}</AreaChart></ResponsiveContainer></div></section>}
function ManageCash({anchors,cashflows,reload}){return <section className="card wide"><h2>Cashflow items</h2><AnchorForm reload={reload}/><CashflowForm reload={reload}/><h3>Anchors</h3><div className="list">{anchors.map(a=><div className="rowitem" key={a.id}><span>{a.date}</span><b>{money(a.amount)}</b><small>{a.note}</small><button onClick={async()=>{await api(`/api/anchors/${a.id}`,{method:'DELETE'});reload();}}>Delete</button></div>)}</div><h3>Income & expenses</h3><div className="list">{cashflows.map(c=><div className={`rowitem ${!c.active?'muted':''}`} key={c.id}><span>{c.label}</span><b className={c.direction}>{c.direction==='income'?'+':'-'}{money(c.amount)}</b><small>{c.kind} {c.frequency||''} from {c.start_date} · ends {c.end_type}{c.end_date?` ${c.end_date}`:''}{c.end_occurrences?` ${c.end_occurrences}x`:''}</small><button onClick={async()=>{await api(`/api/cashflows/${c.id}/toggle`,{method:'PATCH'});reload();}}>{c.active?'Pause':'Resume'}</button><button onClick={async()=>{await api(`/api/cashflows/${c.id}`,{method:'DELETE'});reload();}}>Delete</button></div>)}</div></section>}
function AnchorForm({reload}){const [f,setF]=useState({date:today(),amount:'',note:''}); async function save(){await api('/api/anchors',{method:'POST',body:JSON.stringify({...f,amount:Number(f.amount)})}); setF({...f,amount:'',note:''}); reload();} return <div className="form"><input type="date" value={f.date} onChange={e=>setF({...f,date:e.target.value})}/><input type="number" placeholder="Anchor amount" value={f.amount} onChange={e=>setF({...f,amount:e.target.value})}/><input placeholder="Note" value={f.note} onChange={e=>setF({...f,note:e.target.value})}/><button onClick={save}>Add anchor</button></div>}
function CashflowForm({reload}){const [f,setF]=useState({label:'',amount:'',direction:'expense',kind:'recurring',frequency:'monthly',start_date:today(),end_type:'never',end_date:'',end_occurrences:'',active:true}); async function save(){const payload={...f,amount:Number(f.amount),frequency:f.kind==='one_off'?null:f.frequency,end_date:f.end_type==='end_date'?f.end_date:null,end_occurrences:f.end_type==='occurrences'?Number(f.end_occurrences):null}; await api('/api/cashflows',{method:'POST',body:JSON.stringify(payload)}); setF({...f,label:'',amount:''}); reload();} return <div className="form"><input placeholder="Label" value={f.label} onChange={e=>setF({...f,label:e.target.value})}/><input type="number" placeholder="Amount" value={f.amount} onChange={e=>setF({...f,amount:e.target.value})}/><select value={f.direction} onChange={e=>setF({...f,direction:e.target.value})}><option>expense</option><option>income</option></select><select value={f.kind} onChange={e=>setF({...f,kind:e.target.value})}><option value="recurring">recurring</option><option value="one_off">one-off</option></select>{f.kind==='recurring'&&<select value={f.frequency} onChange={e=>setF({...f,frequency:e.target.value})}>{['weekly','fortnightly','monthly','quarterly','annually'].map(x=><option key={x}>{x}</option>)}</select>}<input type="date" value={f.start_date} onChange={e=>setF({...f,start_date:e.target.value})}/><select value={f.end_type} onChange={e=>setF({...f,end_type:e.target.value})}><option value="never">never</option><option value="end_date">end date</option><option value="occurrences">after N occurrences</option></select>{f.end_type==='end_date'&&<input type="date" value={f.end_date} onChange={e=>setF({...f,end_date:e.target.value})}/>} {f.end_type==='occurrences'&&<input type="number" placeholder="Occurrences" value={f.end_occurrences} onChange={e=>setF({...f,end_occurrences:e.target.value})}/>}<button onClick={save}>Add cashflow</button></div>}
function PortfolioSection({holdings,portfolio,reload}){async function refresh(){setTimeout(reload,0); await api('/api/portfolio?refresh=true'); reload();} return <section className="card wide"><div className="split"><h2>Portfolio</h2><button onClick={refresh}>Refresh quotes</button></div><HoldingForm reload={reload}/><div className="tiles"><div><p className="eyebrow">Market value</p><h3>{money(portfolio?.totals.market_value_aud)}</h3></div><div><p className="eyebrow">Cost basis</p><h3>{money(portfolio?.totals.cost_basis_aud)}</h3></div><div><p className="eyebrow">Unrealised P/L</p><h3 className={portfolio?.totals.pl_aud>=0?'income':'expense'}>{money(portfolio?.totals.pl_aud)} ({pct(portfolio?.totals.pl_pct)})</h3></div></div><div className="charts"><ResponsiveContainer width="100%" height={260}><PieChart><Pie data={portfolio?.holdings||[]} dataKey="market_value_aud" nameKey="ticker" outerRadius={90} label>{(portfolio?.holdings||[]).map((_,i)=><Cell key={i} fill={['#38bdf8','#22c55e','#f59e0b','#a78bfa','#fb7185'][i%5]}/>)}</Pie><Legend/></PieChart></ResponsiveContainer><ResponsiveContainer width="100%" height={260}><BarChart data={portfolio?.holdings||[]}><CartesianGrid strokeDasharray="3 3" stroke="#233047"/><XAxis dataKey="ticker" tick={{fill:'#9fb1c8'}}/><YAxis tick={{fill:'#9fb1c8'}}/><Tooltip formatter={v=>money(v)}/><Bar dataKey="pl_aud">{(portfolio?.holdings||[]).map((h,i)=><Cell key={i} fill={h.pl_aud>=0?'#22c55e':'#fb7185'}/>)}</Bar></BarChart></ResponsiveContainer></div><div className="table"><table><thead><tr><th>Ticker</th><th>Shares</th><th>Avg cost</th><th>Current</th><th>Market value</th><th>P/L</th><th>Weight</th><th></th></tr></thead><tbody>{(portfolio?.holdings||[]).map(h=><tr key={h.id}><td>{h.ticker}<small>{h.currency}</small></td><td>{h.shares}</td><td>{money(h.cost_per_share,h.currency)}</td><td>{money(h.current_price,h.currency)}<small>{h.price_as_of?'as of '+new Date(h.price_as_of).toLocaleString():'stale/unavailable'}</small></td><td>{money(h.market_value_aud)}<small>{money(h.market_value_native,h.currency)} native</small></td><td className={h.pl_aud>=0?'income':'expense'}>{money(h.pl_aud)}<small>{pct(h.pl_pct)}</small></td><td>{pct(h.weight_pct)}</td><td><button onClick={async()=>{await api(`/api/holdings/${h.id}`,{method:'DELETE'});reload();}}>Delete</button></td></tr>)}</tbody></table></div></section>}
function HoldingForm({reload}){const [f,setF]=useState({ticker:'',shares:'',cost_per_share:'',currency:'AUD',opened_date:today()}); async function save(){await api('/api/holdings',{method:'POST',body:JSON.stringify({...f,shares:Number(f.shares),cost_per_share:Number(f.cost_per_share)})}); setF({...f,ticker:'',shares:'',cost_per_share:''}); reload();} return <div className="form"><input placeholder="Ticker e.g. VAS.AX, AAPL, ASML.AS" value={f.ticker} onChange={e=>setF({...f,ticker:e.target.value.toUpperCase()})}/><input type="number" placeholder="Shares" value={f.shares} onChange={e=>setF({...f,shares:e.target.value})}/><input type="number" placeholder="Price paid / share" value={f.cost_per_share} onChange={e=>setF({...f,cost_per_share:e.target.value})}/><select value={f.currency} onChange={e=>setF({...f,currency:e.target.value})}><option>AUD</option><option>USD</option><option>EUR</option></select><input type="date" value={f.opened_date} onChange={e=>setF({...f,opened_date:e.target.value})}/><button onClick={save}>Add holding</button></div>}
createRoot(document.getElementById('root')).render(<App/>);
